# Generated by Django 6.0.1 on 2026-01-09 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_transaction_cashier_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='cashier_id',
            new_name='cashier',
        ),
    ]
